### PR TITLE
Backport the SM spinjump behavior setting toggle

### PR DESCRIPTION
**Pull request by RebelusQuo**
The v11 Combo rando will allow for toggling the separate spinjump behavior. To keep the execution timing neutral between each setting the assembler code was adjusted. This commit backports the changed implementation so that the SpriteSomething application also produces race legal rom files.

### CODE REVIEW

**Comment by RebelusQuo** [comment]
Added a missing comma which I was sure I fixed already... *derp*

**Comment by RebelusQuo** [comment]
Has there been any discussions concerning this PR? Would love to have this integrated before v11 of the combo is released.

**Comment by Artheau** [comment]
Your pull request is specific to the combo randomizer implementation and its interaction with other game variants is not known at this time.  For this reason, integrating it without adjustment may break some of the existing functionality.  In the next version of SpriteSomething, some refactor of the GUI is planned, and it makes sense at that time to try to add this as an "optional" change.

**Comment by RebelusQuo** [comment]
Alright, what interaction, or interactions, are the issue? is it any of the following?
- Relocation of the control code routine at $90:8688 to $90:F640
- Spinjump configuration flag at $B4F500
Or even more issues beyond those?

**Comment by Artheau** [comment]
Moved these changes to #83

**Pull request closed without merging**
