### PR TITLE
Stable

### PR DESCRIPTION
**Pull request by Pneu-matic**
I called the filename in export_all_images_to_PNG to get the original image. There must be a better way, but it seems to work.

### CODE REVIEW

**Comment by miketrethewey** [comment]
Why are you checking the width of the image to make sure they're the same? Would a different calculation make more sense?

**Comment by Pneu-matic** [comment]
It's to check if it's dealing with the link sprite.

**Comment by miketrethewey** [comment]
Ah ha, gotcha.

**Comment by Pneu-matic** [comment]
That's also why the image load is inside the if statement. If it tries to load a .zspr, PIL doesn't recognize it and it crashes.

**Pull request merged**
